require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ComedyClubsController do

  # This should return the minimal set of attributes required to create a valid
  # ComedyClub. As you add validations to ComedyClub, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ComedyClubsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all comedy_clubs as @comedy_clubs" do
      comedy_club = ComedyClub.create! valid_attributes
      get :index, {}, valid_session
      assigns(:comedy_clubs).should eq([comedy_club])
    end
  end

  describe "GET show" do
    it "assigns the requested comedy_club as @comedy_club" do
      comedy_club = ComedyClub.create! valid_attributes
      get :show, {:id => comedy_club.to_param}, valid_session
      assigns(:comedy_club).should eq(comedy_club)
    end
  end

  describe "GET new" do
    it "assigns a new comedy_club as @comedy_club" do
      get :new, {}, valid_session
      assigns(:comedy_club).should be_a_new(ComedyClub)
    end
  end

  describe "GET edit" do
    it "assigns the requested comedy_club as @comedy_club" do
      comedy_club = ComedyClub.create! valid_attributes
      get :edit, {:id => comedy_club.to_param}, valid_session
      assigns(:comedy_club).should eq(comedy_club)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ComedyClub" do
        expect {
          post :create, {:comedy_club => valid_attributes}, valid_session
        }.to change(ComedyClub, :count).by(1)
      end

      it "assigns a newly created comedy_club as @comedy_club" do
        post :create, {:comedy_club => valid_attributes}, valid_session
        assigns(:comedy_club).should be_a(ComedyClub)
        assigns(:comedy_club).should be_persisted
      end

      it "redirects to the created comedy_club" do
        post :create, {:comedy_club => valid_attributes}, valid_session
        response.should redirect_to(ComedyClub.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved comedy_club as @comedy_club" do
        # Trigger the behavior that occurs when invalid params are submitted
        ComedyClub.any_instance.stub(:save).and_return(false)
        post :create, {:comedy_club => { "name" => "invalid value" }}, valid_session
        assigns(:comedy_club).should be_a_new(ComedyClub)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ComedyClub.any_instance.stub(:save).and_return(false)
        post :create, {:comedy_club => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested comedy_club" do
        comedy_club = ComedyClub.create! valid_attributes
        # Assuming there are no other comedy_clubs in the database, this
        # specifies that the ComedyClub created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ComedyClub.any_instance.should_receive(:update).with({ "name" => "MyString" })
        put :update, {:id => comedy_club.to_param, :comedy_club => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested comedy_club as @comedy_club" do
        comedy_club = ComedyClub.create! valid_attributes
        put :update, {:id => comedy_club.to_param, :comedy_club => valid_attributes}, valid_session
        assigns(:comedy_club).should eq(comedy_club)
      end

      it "redirects to the comedy_club" do
        comedy_club = ComedyClub.create! valid_attributes
        put :update, {:id => comedy_club.to_param, :comedy_club => valid_attributes}, valid_session
        response.should redirect_to(comedy_club)
      end
    end

    describe "with invalid params" do
      it "assigns the comedy_club as @comedy_club" do
        comedy_club = ComedyClub.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ComedyClub.any_instance.stub(:save).and_return(false)
        put :update, {:id => comedy_club.to_param, :comedy_club => { "name" => "invalid value" }}, valid_session
        assigns(:comedy_club).should eq(comedy_club)
      end

      it "re-renders the 'edit' template" do
        comedy_club = ComedyClub.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ComedyClub.any_instance.stub(:save).and_return(false)
        put :update, {:id => comedy_club.to_param, :comedy_club => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested comedy_club" do
      comedy_club = ComedyClub.create! valid_attributes
      expect {
        delete :destroy, {:id => comedy_club.to_param}, valid_session
      }.to change(ComedyClub, :count).by(-1)
    end

    it "redirects to the comedy_clubs list" do
      comedy_club = ComedyClub.create! valid_attributes
      delete :destroy, {:id => comedy_club.to_param}, valid_session
      response.should redirect_to(comedy_clubs_url)
    end
  end

end
